baseURL: "https://ewaroza.github.io/sparta/"
title: Sparta
paginate: 8
# theme: hugo-primer
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sparta
  description: 'Sparta description'
  author: Spartanin
  # author: ["Me", "You"] # multiple authors

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: ''

  label:
    text: "Home"
    icon: /sparta/logo.jpg
    iconHeight: 55


  # home-info mode
  homeInfoParams:
    Title: "Thermopylae in Modern Polish Culture"
    Content: >
      This site was created to celebrate [the 2500 anniversary of the Battle of Thermopylae](https://thermopylae2500.wordpress.com/about/) together with the [Hellenic Society](https://www.hellenicsociety.org.uk/). It presents a research project *Sparta in Polish Literature and Culture – from the Old Polish Period to the 20th Century: Between the Reception of Greek Heritage and the Search for National Identity* and discusses the central role of Thermopylae in the Polish reception of Sparta.
    
