baseURL: "https://ewaroza.github.io/greko/"
title: Greko
paginate: 8
# theme: hugo-primer
theme: blist

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

DefaultContentLanguage: "en"
DefaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: "content/en" #English
    weight: 1
    languageName: "English"
    params:
      introTitle: "Po co nam greko?"
      introSubtitle: "Greko (grekański, grecko-kalabryjski) to język mieszkańców już tylko kilku miejscowości w południowej Kalabrii. Liczba jego użytkowników stale spada: w XX wieku przestał być przekazywany następnym pokoleniom. Coraz mniej osób potrafi i chce nim mówić. Przyszłość greko jest więc bardzo niepewna, grozi mu zapomnienie.   
      
      Jednak w historii greko i mówiącej nim społeczności splata się wiele wątków, których znaczenie wykracza poza granice regionu i poza znaczenie samego języka. Refleksja nad kulturą grekańską skłania do zadania pytania o wartość tradycji skonfrontowanej z obietnicami, jakie roztaczają hasła nowoczesności i postępu. Historia Grekan przestrzega przed spustoszeniem i stratami, które mogą przynieść z jednej strony źle rozumiana modernizacja, a z drugiej bezrefleksyjna nostalgia za przeszłością. W końcu, mówienie i pisanie w greko to akt społecznej i politycznej interwencji, a skupienie uwagi na zagrożonym języku pozwala zawiesić neoliberalną logikę zysku, zgodnie z którą warto inwestować czas i wysiłek w poznawanie tylko tych języków, których znajomość szybko przełoży się na łatwe do zmierzenia korzyści."
      introPhoto: "/picture.jpg"
#      logo: "/blist-logo.png"
    menu:
      main:
        -
          name: "Posty"
          url: "/"
          weight: 1
        -
          name: "O stronie"
          url: "/about/"
          weight: 2
        -
         name: "Bibliografia"
         url: "/biblio/"
         weight: 3
#        -
#          name: "Top Post"
#          url: "/en/blog/emoji-support/"
#          weight: 4

menu:
  main:
    name: "About"
    url: "/about"

build:
  writeStats: true

outputs:
  home: ["HTML", "RSS", "JSON"]

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Greko
  description: 'Greko description'
  author: Ewa Janion
  # author: ["Me", "You"] # multiple authors
  ascentColor: bg-gray-100

  hideMeta: true

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: ''

  label:
    text: "Home"
    icon: /sparta/logo.jpg
    iconHeight: 115


  # home-info mode
  homeInfoParams:
    Title: "Thermopylae in Modern Polish Culture"
    Content: >
      This site was created to celebrate [the 2500 anniversary of the Battle of Thermopylae](https://thermopylae2500.wordpress.com/about/) together with the [Hellenic Society](https://www.hellenicsociety.org.uk/). It presents a research project *Sparta in Polish Literature and Culture – from the Old Polish Period to the 20th Century: Between the Reception of Greek Heritage and the Search for National Identity* and discusses the central role of Thermopylae in the Polish reception of Sparta.
    
